"""Add TOTP MFA fields

Revision ID: 50014f9013dd
Revises: 7ca11ee1dc57
Create Date: 2026-04-19 18:26:38.722376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50014f9013dd'
down_revision = '7ca11ee1dc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mfa_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mfa_configured', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_configured')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
