"""empty message

Revision ID: 5bf4f876c32a
Revises: 23f2b9768fb1
Create Date: 2026-04-23 06:19:05.500881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf4f876c32a'
down_revision = '23f2b9768fb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column(
             'last_login',
             existing_type=sa.VARCHAR(length=255),
             type_=sa.DateTime(),
             postgresql_using="last_login::timestamp"
        )
               

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
