"""Update alerts model for alert page

Revision ID: aeeaa7e98b3c
Revises: 3d94f125173d
Create Date: 2026-04-20 09:55:40.601109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeeaa7e98b3c'
down_revision = '3d94f125173d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endpoint', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cvss_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ml_severity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('email_sent')
        batch_op.drop_column('ml_severity')
        batch_op.drop_column('cvss_score')
        batch_op.drop_column('category')
        batch_op.drop_column('endpoint')

    # ### end Alembic commands ###
